octopus:
  environments:
    - staging
    - production
  replicated: true
  fully_replicated: true 
  staging:
    slave1:
      host:  scalablemaster-test1-replica.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      adapter: mysql2
      database: rails_app
      username: root
      password: password
      reconnect: false
  production:
    slave1:
      host:  scalablemaster-test1-replica.cz2moefkl3s1.us-west-2.rds.amazonaws.com
      adapter: mysql2
      database: rails_app
      username: root
      password: password
      reconnect: true